
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Rooxo', '15 Chive Trail', '$6.24', 'Space-saving broom holder for organized cleaning supplies.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Centizu', '280 Logan Avenue', '$9.76', 'Healthy granola made with oats and honey.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Aibox', '6703 Glendale Avenue', '$3.80', 'Perfectly balanced sweet and tangy BBQ sauce for dipping or grilling.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Devcast', '3 Golf Avenue', '$4.71', 'Convenient carrier for transporting yoga mat.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Twitterlist', '593 Jana Terrace', '$5.86', 'Spicy salsa made with black beans and tomatoes.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Topicshots', '33 Sugar Lane', '$8.37', 'Durable jump rope for cardio workouts.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Devcast', '97 Corry Pass', '$5.52', 'Versatile electric skillet for stir-frying and searing.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Oloo', '3 Badeau Park', '$1.98', 'Ergonomic mouse designed for gamers with high DPI.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Pixoboo', '97964 Loeprich Terrace', '$5.94', 'Fresh kale salad with a zesty lemon dressing, great as a side dish.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Lazz', '57963 Memorial Road', '$6.79', 'Toy drone that flies with gestures and is easy to control.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Yakidoo', '01 Montana Center', '$5.52', 'Hearty stew made with lentils and mixed vegetables, vegan-friendly.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Yotz', '6610 Luster Parkway', '$9.35', 'Wi-Fi enabled plug for controlling devices from your smartphone.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Edgeclub', '122 Carioca Terrace', '$0.05', 'Roasted Brussels sprouts drizzled with balsamic glaze.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Pixope', '0 Wayridge Place', '$5.11', 'Compact keyboard for tablets and smartphones.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Geba', '4 Paget Circle', '$9.84', 'Easy-to-heat frozen burritos for a quick meal.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Blogspan', '4 Vahlen Alley', '$8.15', 'A casual striped long sleeve shirt that''s perfect for layering.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('DabZ', '9 Sage Drive', '$8.97', 'Baked kale chips seasoned for a healthy, crunchy snack.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Jayo', '47481 Gerald Place', '$4.96', 'Educational robotics kit for building and programming.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Mita', '89176 Lakewood Gardens Point', '$4.88', 'Deliciously creamy spinach dip, perfect for parties.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Topicstorm', '8 Little Fleur Circle', '$6.73', 'Padded laptop sleeve for protection against scratches.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Twinder', '8 Grim Hill', '$4.81', 'Designed for comfort and performance during workouts.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Voonte', '8699 Haas Way', '$7.06', 'Hands-on experience with science and engineering projects.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Geba', '6907 Everett Court', '$2.57', 'Warm oatmeal flavored with apple and cinnamon.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Kimia', '554 Spaight Avenue', '$4.03', 'Quick oatmeal cups with banana and nut flavor, great for breakfast.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Vinder', '57 Waubesa Lane', '$4.55', 'Lightly salted frozen edamame, a protein-packed snack.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Dynabox', '03544 5th Way', '$6.14', 'Creamy mashed potatoes infused with roasted garlic flavor.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Topicstorm', '18351 Thompson Pass', '$9.49', 'Simple tool to train your pet with positive reinforcement.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Eadel', '259 Maple Wood Avenue', '$3.33', 'Nutritious protein bar with cherry and almond flavor, great for on-the-go.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Blogtags', '8 Basil Drive', '$5.82', 'A warm and stylish puffer coat perfect for winter weather.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Flashpoint', '79 Badeau Crossing', '$6.58', 'A warm and sustainable wool scarf for chilly days.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Feedmix', '4418 Brown Hill', '$4.85', 'All-in-one kit for brewing beer at home.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Layo', '199 South Street', '$2.06', 'Organize travel documents, passport, and cards.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Yakitri', '70 Scott Plaza', '$1.11', 'Compact charcoal grill perfect for tailgating.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Devbug', '061 Elka Point', '$0.46', 'Bell peppers stuffed with rice and vegetables');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Blogtag', '0 Armistice Parkway', '$4.36', 'Hearty beef stew with vegetables, ready to heat and serve.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Miboo', '01355 Lotheville Alley', '$4.04', 'Floral and refreshing herbal tea, great hot or iced.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Yadel', '31 Eggendart Alley', '$6.27', 'Ready-to-eat salad with kale, lemon, and cheese.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Mita', '5001 Starling Terrace', '$5.56', 'Lightweight water filter for outdoor adventures.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Omba', '20 Declaration Street', '$4.85', 'Lightweight and durable tent for camping trips.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Kamba', '6099 Portage Drive', '$9.00', 'Healthy salad made with chickpeas, vegetables, and a lemon dressing.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Gabspot', '67359 Sunbrook Alley', '$1.38', 'Light and crunchy rice cakes with a variety of flavors.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Skiba', '7 Morning Circle', '$3.17', 'Comfortable and stretchy legging pants perfect for workouts or daily wear.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Skipfire', '5 Arrowood Hill', '$9.28', 'Functional leggings designed for maximum comfort during workouts.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Myworks', '45005 Hermina Park', '$0.40', 'Crispy sweet potato fries, perfectly seasoned and baked to perfection.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Ooba', '680 Chinook Place', '$7.27', 'Stylish faux leather leggings for a trendy outfit.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Mybuzz', '8017 School Pass', '$3.63', 'Compact storage for your jewelry while traveling.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Pixonyx', '32 Declaration Lane', '$5.44', 'Eco-friendly coffee filter for brewing.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Centimia', '8 Rusk Center', '$6.69', 'Stylish bookends to keep books organized on shelves.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Innojam', '05208 Spaight Lane', '$6.98', 'Comfortable eye mask that includes noise-canceling ear plugs.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Meetz', '69 Carpenter Parkway', '$5.45', 'Strong magnetic holder for smartphones in cars.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Oyoba', '7460 Merrick Parkway', '$0.50', 'Thin rice noodles, ideal for stir-fries and soups.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Trunyx', '3 Mallard Plaza', '$8.87', 'Spiralized zucchini, a healthy alternative to pasta.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Dynazzy', '86 Anderson Road', '$9.44', 'Compact organizer for cosmetics during travel.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Tagcat', '3804 Bartelt Park', '$5.66', 'Soft and comfortable robe, perfect for lounging at home.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Divanoodle', '04191 Upham Center', '$5.86', 'Compact alarm for personal safety and security.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Brainverse', '6643 Marquette Street', '$0.73', 'A blend of dried Italian herbs for cooking.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Rhyloo', '345 Spenser Drive', '$2.33', 'All ingredients included for delicious chicken fajitas.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Voonix', '2262 John Wall Center', '$7.89', 'Spacious duffle bag for weekend getaways.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Youfeed', '1647 Graceland Drive', '$9.83', 'Seasoning mix for making crispy and flavorful potato wedges.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Latz', '8 Farragut Hill', '$0.73', 'Essential ingredient for baking and cooking.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Zava', '31 Memorial Way', '$3.31', 'Salsa made with fire-roasted tomatoes for an authentic flavor.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Quimba', '94864 Shopko Lane', '$6.70', 'Nutritious protein bars for on-the-go snacking.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Dynabox', '0 Northview Terrace', '$4.37', 'Heavy-duty bicycle lock for security.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Realbuzz', '63555 Nobel Pass', '$2.38', 'Ergonomic desk that adjusts height for standing or sitting.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Photojam', '40 Lerdahl Center', '$4.32', 'Stylish black leather jacket featuring a zip-up front and multiple pockets.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Aimbu', '2579 Vahlen Point', '$4.38', 'Bold combat boots that make a statement with any outfit.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Ntag', '84 Blaine Road', '$5.50', 'Stylish baskets for organizing various items in your home.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Vidoo', '796 Rieder Plaza', '$7.16', 'High-capacity power bank for charging devices on the go.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Tekfly', '69 Talisman Road', '$0.33', 'Refreshing apple juice, 100% juice with no added sugar.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Meeveo', '012 Laurel Point', '$9.02', 'Healthier way to make popcorn in the microwave without oil.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Pixonyx', '17 Division Center', '$3.81', 'Mixed fresh vegetables for stir-frying or roasting.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Quinu', '26795 Reindahl Junction', '$2.60', 'Lightweight, expandable hoses for easy handling.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Jabbercube', '5075 Nova Pass', '$6.16', 'No-bake protein balls with chocolate and coconut flavors.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Roomm', '01855 Bartillon Plaza', '$8.44', 'Soft glow night light for children''s rooms or bedside.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Roomm', '50 Rusk Street', '$6.68', 'Crunchy seeds perfect for toppings and baking.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Divavu', '677 Anderson Pass', '$2.57', 'Travel-friendly dog bowl that is collapsible for easy storage.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Plajo', '43 Shopko Center', '$5.26', 'Rich and creamy tomato basil soup, perfect with a grilled cheese.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Vipe', '42984 Surrey Pass', '$8.89', 'Frozen pizza loaded with fresh vegetables and mozzarella cheese.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Topiczoom', '32738 Di Loreto Hill', '$3.08', 'Boost your Wi-Fi signal for better coverage.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Feedmix', '06 Kenwood Road', '$0.87', 'Set of decorative ceramic planters for indoor plants.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Skippad', '7041 Larry Pass', '$7.81', 'Deliciously creamy almond milk, perfect for smoothies.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Jabbertype', '946 Waubesa Place', '$4.21', 'Heated stool cover for extra comfort during winter.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Babbleset', '142 Mendota Road', '$6.01', 'A rich pesto made with sun-dried tomatoes and pine nuts.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Katz', '9 Mayfield Circle', '$7.55', 'Steamed edamame tossed in a spicy garlic sauce, great for snacking.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Abatz', '707 Parkside Park', '$2.99', 'Spicy sauce made with chipotle peppers');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Voolia', '71524 High Crossing Road', '$7.03', 'Complete karaoke system with microphones and speakers.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Wikibox', '97 Lawn Pass', '$5.15', 'All-in-one kit for making delicious chicken salad.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Chatterbridge', '22 Valley Edge Trail', '$0.26', 'Color-changing LED lights for home decoration with remote.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Gabcube', '89924 Loomis Alley', '$5.87', 'Tangy sour cream, perfect for dips and toppings.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Gabcube', '22082 Oakridge Plaza', '$6.11', 'Trendy belt bag for hands-free carrying.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Minyx', '307 Oriole Road', '$1.63', 'Absorbent training pads for puppies and kittens.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Thoughtworks', '20988 Mayer Court', '$3.72', 'Marinated chicken thighs with smoked paprika for a smoky flavor.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Rhynoodle', '89376 Hayes Road', '$3.72', 'Stylish baskets for organizing various items in your home.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Zoomzone', '926 Northwestern Parkway', '$2.19', 'Durable yoga strap for deeper stretches.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Vidoo', '55 Donald Junction', '$7.94', 'Stay dry with these stylish waterproof rain boots.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Photobug', '839 Bluejay Parkway', '$1.08', 'Reusable microfiber cloths for environmentally friendly cleaning.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Blogtag', '5 Pankratz Point', '$6.17', 'Mix for homemade cornbread, just add water and bake for a delicious side.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Edgeclub', '660 Duke Crossing', '$4.23', 'Spice blend for creating flavorful vegan taco filling.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Feedmix', '9672 Graceland Parkway', '$3.09', 'Sweet peach halves packed in juice, great for desserts.');
insert into MockStore.dbo.MockStores (Name, Address, Revenue, Description) values ('Topdrive', '930 Mariners Cove Parkway', '$1.19', 'Instant noodles with a spicy Thai sauce for quick meals.');

​
